security:
    encoders:
        # Symfony\Component\Security\Core\User\User: plaintext
        Project\AppBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        # in_memory:
            # memory:
                # users:
                    # user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    # admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous:  true
            provider:   main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: /index
            remember_me:
                key: %secret% 

            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"


    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
