security:
    encoders:
        # Symfony\Component\Security\Core\User\User: plaintext
        Project\AppBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_STUDENT:     ROLE_STUDENT
        ROLE_SPEAKER:     ROLE_SPEAKER  
        ROLE_MANAGER:     [ROLE_SPEAKER, ROLE_MANAGER]
        ROLE_ADMIN:       [ROLE_MANAGER, ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: false
                default_target_path:            /index
            logout:
                path:   fos_user_security_logout
                target: /
            remember_me:
                key: %secret% 

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administrator, roles: ROLE_ADMIN }
        - { path: ^/manager, roles: ROLE_MANAGER }
        - { path: ^/speaker, roles: ROLE_SPEAKER }