<?php

namespace Project\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CriterionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriterionRepository extends EntityRepository
{
    /**
     * Find each criterion of an evaluation given
     *
     * @param $eval
     * @return array
     */
    public function findAllByEvaluation(Evaluation $eval)
    {
        return $this->getEntityManager()
                ->createQuery(
                        'SELECT c
                        FROM ProjectAppBundle:Criterion c
                        WHERE c.evaluation = :eval'
                )
                ->setParameter('eval', $eval)
                ->getResult();
    }
}
