<?php

namespace Project\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonRepository extends EntityRepository
{
    /**
     * Find the today lesson
     *
     * @return array
     */
    public function findTodayLessonId()
    {
        $em = $this->getEntityManager();

        return $em->createQuery(
                '
                SELECT l.id
                FROM ProjectAppBundle:Lesson l
                WHERE CURRENT_TIMESTAMP()  BETWEEN l.startDate AND l.endDate
                '
            )
            ->getResult();
    }
}
