<?php

namespace Project\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Lesson_has_StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonStudentRepository extends EntityRepository
{
    public function findStudentsByLesson($lesson_id)
    {
        $em = $this->getEntityManager();

        return $em->createQuery(
                '
                SELECT ls.studentUserId
                FROM ProjectAppBundle:LessonStudent ls
                WHERE ls.lessonId = :id
                '
            )
            ->setParameter('id', $lesson_id)
            ->getArrayResult();
    }
}
