<?php

namespace Project\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Speaker_has_lessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeakerLessonRepository extends EntityRepository
{
    /**
     * Find all lessons of a speaker
     *
     * @param $speaker_id
     * @return array
     */
    public function findLessonsBySpeaker($speaker_id)
    {
        $em = $this->getEntityManager();

        return $em->createQuery(
            "
            SELECT sl.lessonId
            FROM ProjectAppBundle:SpeakerLesson sl
            WHERE sl.speakerUserId = :id
            "
            )
            ->setParameter('id', $speaker_id)
            ->getArrayResult();
    }
}
