<?php

namespace Project\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Speaker_has_lessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Speaker_has_lessonRepository extends EntityRepository
{
    public function findLessonsBySpeaker($speaker_id)
    {
        $em = $this->getEntityManager();

        return $em->createQuery(
            'SELECT lesson_id FROM ProjectAppBundle:Speaker_has_lesson WHERE speaker_id = :id'
            )
            ->setParameter('id', $speaker_id)
            ->getArrayResult();
    }
}
