<?php

namespace Project\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends EntityRepository
{
    /**
     * Create a json of students of a promotion
     *
     * @param int $promotion id of the promotion to convert to a json.
     * @return string JSON that contain the element of a promotion.
     */
    public function toJson($promotion)
    {
        $jsonData = array();
        $qb = $this->createQueryBuilder('s');

        $qb->where('s.promotion = :promotion')
            ->setParameter('promotion', $promotion);

        $students = $qb->getQuery()
            ->getResult();

        foreach ($students as $student) {
            $user = $student->getUser();

            $jsonData[] = array(
                                'name' => $user->getUsername(),
                                'surname' => $user->getSurname(),
                                'email' => $user->getEmail(),
                                'last_login' => $user->getLastLogin(),
                                'phone' => $user->getPhone(),
                                'corporation' => $user->getCorporation()
                                );
        }

        return json_encode($jsonData);
    }
}
