<?php

namespace Project\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StudentEvaluationCriterionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentEvaluationCriterionRepository extends EntityRepository
{
    public function findOneByCritEval(Criterion $crit, StudentEvaluation $se) {
        $em = $this->getEntityManager();

        return $em->createQuery('
                SELECT sec
                FROM ProjectAppBundle:StudentEvaluationCriterion sec
                WHERE sec.studentEvaluation = :se
                AND sec.criterion = :criterion
            ')
                ->setParameters(array(
                        'se' => $se,
                        'criterion' => $crit
                ))
                ->getOneOrNullResult();
    }
}
