<?php

namespace Project\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StudentEvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentEvaluationRepository extends EntityRepository
{
    public function findStudentsByEvaluation (Evaluation $eval ) {
        $em = $this->getEntityManager();

        $students = array();

        $students_id = $em->createQuery(
                        "
                        SELECT IDENTITY (se.student)
                        FROM ProjectAppBundle:StudentEvaluation se
                        WHERE se.evaluation = :eval
                        "
                )
                ->setParameter('eval', $eval)
                ->getArrayResult();

        foreach($students_id as $id) {
            $usersId[] = $em->getRepository('ProjectAppBundle:Student')
                    ->findOneById($id)
                    ->getUserId();
        }
        if(isset($usersId)){
            foreach($usersId as $user) {
                $students[] = $em->getRepository('ProjectAppBundle:User')
                        ->findOneById($user);
            }
        }

        return $students;
    }
}
