<?php

namespace Project\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * Find user by its id
     *
     * @param $id
     * @return User
     */
    public function findUserById($id)
    {
        $em = $this->getEntityManager();
        return $em->createQuery(
                    '
                    SELECT u
                    FROM ProjectAppBundle:User u
                    WHERE u.id = :id
                    '
                )
                ->setParameter('id', $id)
                ->getSingleResult();
    }
}
