# Manager

project_app_manager_module:
    path:     /manager/module
    defaults: { _controller: ProjectAppBundle:Module:index }

project_app_manager_module_create:
    path:     /manager/module_create
    defaults: { _controller: ProjectAppBundle:Module:create }
