project_app_index:
    path:     /index
    defaults: { _controller: ProjectAppBundle:User:index }

# Manager

project_app_manager_formation_create:
    path:     /manager/formation_create
    defaults: { _controller: ProjectAppBundle:Formation:create }

project_app_manager_promotion:
    path:     /manager/promotion
    defaults: { _controller: ProjectAppBundle:Promotion:index }

project_app_manager_promotion_create:
    path:     /manager/promotion_create
    defaults: { _controller: ProjectAppBundle:Promotion:create }

project_app_manager_module:
    path:     /manager/module
    defaults: { _controller: ProjectAppBundle:Module:index }

project_app_manager_module_create:
    path:     /manager/module_create
    defaults: { _controller: ProjectAppBundle:Module:create }

# Speaker

project_app_speaker:
    path:     /speaker
    defaults: { _controller: ProjectAppBundle:Speaker:index }

project_app_speaker_missings:
    path:     /speaker/missings
    defaults: { _controller: ProjectAppBundle:Speaker:missings }

# Student